name: package-test

on:
  push:
    branches: [master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  package-test:
    runs-on: ubuntu-latest
    name: Package Test

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn install --frozen-lockfile --network-timeout 1000000
    - run: yarn build-report
    - run: sudo apt-get install xvfb

    - run: xvfb-run --auto-servernum bash $GITHUB_WORKSPACE/lighthouse-core/scripts/release/package-test.sh

    # Fail if any changes were written to source files.
    - run: git diff --exit-code

  package-test-fr:
    runs-on: ubuntu-latest
    name: Package Test Fraggle Rock

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn install --frozen-lockfile --network-timeout 1000000
    - run: yarn build-report
    - run: sudo apt-get install xvfb

    # Disabled to fix CI while we investigate what the bug is.
    #   perf-diagnostics-third-party, oopif-requests, oopif-scripts
    - run: xvfb-run --auto-servernum bash $GITHUB_WORKSPACE/lighthouse-core/scripts/release/package-test.sh --fraggle-rock --invert-match perf-diagnostics-third-party oopif-requests oopif-scripts

    # Fail if any changes were written to source files.
    - run: git diff --exit-code
